# Script: sanitize_ai_mentions.ps1
# Searches repository for common AI/vendor mentions and replaces them with neutral terms.
# Skips binary files and patterns in .gitignore; will not add .zip files or other binaries.

$ErrorActionPreference = 'Stop'

Write-Host "Collecting candidate text files..."
$exts = @('.md','.txt','.mdown','.markdown','.json','.cpp','.h','.hpp','.c','.cc','.cs','.py','.cmake','.yml','.yaml','.ini','.bat','.sh','.ps1')
$files = Get-ChildItem -Path . -Recurse -File -Force | Where-Object {
    $exts -contains $_.Extension.ToLower() -and ($_.FullName -notmatch '\\.git\\') -and ($_.FullName -notmatch '\\.(zip|exe|dll|so|bin)$')
}

if (-not $files) { Write-Host "No candidate files found. Exiting."; exit 0 }

$replacements = @(
    @{pattern='(?i)\bChatGPT\b'; replace='tooling'},
    @{pattern='(?i)\bOpenAI\b'; replace='tooling'},
    @{pattern='(?i)\bAnthropic\b'; replace='tooling'},
    @{pattern='(?i)\bClaude\b'; replace='tooling'},
    @{pattern='(?i)\bGPT[- ]?\d*\b'; replace='tooling'},
    @{pattern='(?i)\bAI-assisted\b'; replace='assisted'},
    @{pattern='(?i)\bAI assisted\b'; replace='assisted'},
    @{pattern='(?i)\bgenerated by AI\b'; replace='generated'},
    @{pattern='(?i)\bgenerated by (?:tooling|tooling|tooling|tooling)\b'; replace='generated'},
    @{pattern='(?i)\bBuilt with .*?tooling Code\b'; replace='Built with tooling'},
    @{pattern='(?i)tooling.ai/code'; replace='[tooling]'}
)

$modified = @()

foreach ($file in $files) {
    $path = $file.FullName
    try {
        $content = Get-Content -Raw -Encoding UTF8 -ErrorAction Stop $path
    } catch {
        continue
    }
    if ($null -eq $content -or $content -eq '') {
        continue
    }
    $orig = $content
    foreach ($r in $replacements) {
        try {
            $content = [regex]::Replace($content, $r.pattern, $r.replace)
        } catch {
            Write-Host "Regex replace failed for $path pattern $($r.pattern): $_"
        }
    }
    if ($content -ne $orig) {
        Write-Host "Updating: $path"
        # write back
        Set-Content -Encoding UTF8 -Value $content -Path $path
        git add -- "$path"
        $modified += $path
    }
}

if ($modified.Count -eq 0) { Write-Host "No files modified."; exit 0 }

# Commit and push
Write-Host "Committing ${($modified.Count)} modified files..."
try {
    git commit -m "chore: sanitize AI/vendor mentions (tooling, tooling, tooling, tooling, tooling)" 
} catch {
    Write-Host "Commit failed or nothing to commit: $_"
}

$branch = (git rev-parse --abbrev-ref HEAD).Trim()
Write-Host "Pushing to origin/$branch..."
try {
    git push origin $branch
} catch {
    Write-Host "Push failed: $_"
}

Write-Host "Done. Modified files:"
$modified | ForEach-Object { Write-Host " - $_" }

